;;; uwumacs-compatibility-tests.el --- P03 individual support gates -*- lexical-binding: t; -*-
;; Run in a fresh source-only Windows 30.1 process; no helper initializes packages.
(require 'ert)
(require 'cl-lib)
(require 'package)
(require 'bytecomp)

(defconst uwumacs-acceptance-root
  (file-name-directory (directory-file-name (file-name-directory load-file-name))))
(defconst uwumacs-acceptance-core (expand-file-name "lambda-library/lambda-user/" uwumacs-acceptance-root))
(defconst uwumacs-acceptance-core-files
  '("uwumacs-maps.el" "uwumacs-state.el" "uwumacs-registry.el" "uwumacs-integration-core.el" "uwumacs.el"))
(defconst uwumacs-acceptance-started-fresh (not (featurep 'uwumacs)))

(defun uwumacs-acceptance-load-core ()
  (cl-letf (((symbol-function 'package-install) (lambda (&rest _) (error "Core attempted package installation")))
            ((symbol-function 'package-refresh-contents) (lambda (&rest _) (error "Core attempted archive refresh"))))
    (dolist (file uwumacs-acceptance-core-files)
      (load (expand-file-name file uwumacs-acceptance-core) nil t))))

(defun uwumacs-acceptance-forms (file)
  (with-temp-buffer
    (insert-file-contents file)
    (let (forms)
      (condition-case nil
          (while t (push (read (current-buffer)) forms))
        (end-of-file (nreverse forms))))))

(ert-deftest uwumacs-acceptance-i005-core-load-does-not-acquire-packages ()
  (should uwumacs-acceptance-started-fresh)
  (uwumacs-acceptance-load-core)
  (should (featurep 'uwumacs))
  (should (featurep 'uwumacs-integration-core))
  (should-not uwumacs-integrations)
  (should-not uwumacs-mode))

(ert-deftest uwumacs-acceptance-i007-core-byte-compiles-with-explicit-cl-lib ()
  (dolist (file '("uwumacs-maps.el" "uwumacs-state.el" "uwumacs-registry.el"))
    (should (member '(require 'cl-lib) (uwumacs-acceptance-forms (expand-file-name file uwumacs-acceptance-core)))))
  (let ((directory (make-temp-file "uwu-compile-" t))
        (byte-compile-error-on-warn t)
        (native-comp-jit-compilation nil))
    (unwind-protect
        (let ((load-path (cons directory load-path)))
          (dolist (file uwumacs-acceptance-core-files)
            (copy-file (expand-file-name file uwumacs-acceptance-core) (expand-file-name file directory)))
          (dolist (file uwumacs-acceptance-core-files)
            (should (byte-compile-file (expand-file-name file directory))))
          (should (= 5 (length (directory-files directory nil "\\.elc\\'")))))
      (delete-directory directory t))))

(ert-deftest uwumacs-acceptance-i008-no-obsolete-cl-imports ()
  (dolist (file (directory-files uwumacs-acceptance-core t "\\`uwumacs.*\\.el\\'"))
    (should-not (member '(require 'cl) (uwumacs-acceptance-forms file)))))

(ert-deftest uwumacs-acceptance-i009-windows-30.1-core-source-load ()
  (should (equal emacs-version "30.1"))
  (should (eq system-type 'windows-nt))
  (uwumacs-acceptance-load-core)
  (dolist (feature '(uwumacs-maps uwumacs-state uwumacs-registry uwumacs))
    (should (featurep feature))
    (should (string-suffix-p ".el" (car (cl-find-if (lambda (entry) (member (cons 'provide feature) (cdr entry))) load-history)))))
  (dolist (file '("uwumacs-maps.el" "uwumacs-registry.el"))
    (should (member '(require 'subr-x) (uwumacs-acceptance-forms (expand-file-name file uwumacs-acceptance-core))))))

(ert-deftest uwumacs-acceptance-i010-core-adapter-loads-with-compat ()
  (require 'compat)
  (should (package-built-in-p 'compat '(30 1 9999)))
  (should (file-in-directory-p (locate-library "compat") (expand-file-name "var/uwumacs-compat/windows-30.1/portable/" uwumacs-acceptance-root)))
  (uwumacs-acceptance-load-core)
  (dolist (feature '(compat uwumacs-maps uwumacs-state uwumacs-registry uwumacs-integration-core))
    (should (featurep feature))))

(ert-deftest uwumacs-acceptance-i011-builtin-seq-needs-no-install ()
  (should (package-built-in-p 'seq '(2 24)))
  (should (file-in-directory-p (locate-library "seq") (expand-file-name "var/uwumacs-compat/windows-30.1/portable/" uwumacs-acceptance-root)))
  (dolist (file '("uwumacs-maps.el" "uwumacs-registry.el"))
    (should (member '(require 'seq) (uwumacs-acceptance-forms (expand-file-name file uwumacs-acceptance-core)))))
  (uwumacs-acceptance-load-core)
  (should (featurep 'seq))
  (should-not (assq 'seq uwumacs--registry)))

(ert-deftest uwumacs-acceptance-i018-derived-mode-prefers-nearest-adapter-once ()
  (load (or (getenv "UWUMACS_PARENT_MODE_SOURCE") (error "Set UWUMACS_PARENT_MODE_SOURCE")) nil t)
  (require 'meow)
  (define-derived-mode uwumacs-acceptance-parent-mode fundamental-mode "UwuParent")
  (define-derived-mode uwumacs-acceptance-child-mode uwumacs-acceptance-parent-mode "UwuChild")
  (should (equal (parent-mode-list 'uwumacs-acceptance-child-mode)
                 '(uwumacs-acceptance-parent-mode uwumacs-acceptance-child-mode)))
  (let ((uwumacs--registry nil) (uwumacs-integrations nil)
        (uwumacs-after-integration-hook nil) (setups 0) (callbacks 0))
    (unwind-protect
        (with-temp-buffer
          (uwumacs-acceptance-child-mode)
          (uwumacs-mode 1)
          (add-hook 'uwumacs-after-integration-hook (lambda (_) (cl-incf callbacks)))
          (uwumacs-register-integration 'parent :modes '(uwumacs-acceptance-parent-mode)
            :local-bindings '(("x" ignore "Parent") ("p" backward-char "Inherited")))
          (uwumacs-register-integration 'child :modes '(uwumacs-acceptance-child-mode)
            :local-bindings '(("x" forward-char "Child"))
            :setup (lambda () (cl-incf setups) nil))
          (uwumacs-enable-integration 'parent)
          (uwumacs-enable-integration 'child)
          (dotimes (_ 3) (uwumacs-refresh))
          (should (eq 'forward-char (key-binding (kbd "C-c C-SPC m x"))))
          (should (eq 'backward-char (key-binding (kbd "C-c C-SPC m p"))))
          (should (= setups 1))
          (should (= callbacks 2))
          (let ((entries (plist-get uwumacs--buffer-metadata :localleader)))
            (should (= 1 (cl-count-if (lambda (entry) (eq (plist-get (cdr entry) :owner) 'child)) entries)))))
      (uwumacs-mode -1))))

(ert-deftest uwumacs-acceptance-i019-spinner-preserves-input-and-cancels-timer ()
  (load (or (getenv "UWUMACS_SPINNER_SOURCE") (error "Set UWUMACS_SPINNER_SOURCE")) nil t)
  (with-temp-buffer
    (let* ((indicator (spinner-create 'progress-bar t 100))
           (unread-command-events '(uwumacs-sentinel))
           (overriding-local-map (make-sparse-keymap))
           (overriding-terminal-local-map (make-sparse-keymap))
           (local overriding-local-map) (terminal overriding-terminal-local-map)
           cleanup)
      (unwind-protect
          (progn
            (setq cleanup (spinner-start indicator))
            (should (functionp cleanup))
            (should (spinner--active-p indicator))
            (should (memq (spinner--timer indicator) timer-list))
            (sleep-for 0.06)
            (should (> (spinner--counter indicator) 0))
            (should (equal unread-command-events '(uwumacs-sentinel)))
            (should (eq local overriding-local-map))
            (should (eq terminal overriding-terminal-local-map))
            (funcall cleanup)
            (funcall cleanup)
            (should-not (spinner--active-p indicator))
            (should-not (memq (spinner--timer indicator) timer-list))
            (should-not (memq (spinner--timer indicator) timer-idle-list)))
        (spinner-stop indicator)))))
