;;; uwumacs-registry-tests.el --- Registry behavior -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'meow)
(require 'uwumacs)

(defmacro uwumacs-registry-test-with-registry (&rest body)
  (declare (indent 0))
  `(let ((uwumacs--registry nil)
         (uwumacs-integrations nil)
         (uwumacs-after-integration-hook nil)
         (uwumacs-map-context-function nil)
         (uwumacs-user-leader-map (make-sparse-keymap))
         (uwumacs-user-state-maps nil)
         (uwumacs-registry-test-frames (frame-list))
         (uwumacs-registry-test-frame (selected-frame)))
     (should (fboundp 'uwumacs-register-integration))
     (unwind-protect (progn (uwumacs-mode 1) ,@body)
       (uwumacs-mode -1)
       (when (frame-live-p uwumacs-registry-test-frame)
         (select-frame uwumacs-registry-test-frame))
       (dolist (frame (seq-difference (frame-list) uwumacs-registry-test-frames))
         (when (frame-live-p frame) (delete-frame frame t))))))

(defun uwumacs-registry-test-status (id)
  (plist-get (cdr (assq id uwumacs--registry)) :status))

(define-derived-mode uwumacs-registry-parent-mode fundamental-mode "UwuParent")
(define-derived-mode uwumacs-registry-child-mode uwumacs-registry-parent-mode "UwuChild")

(ert-deftest uwumacs-registry-validates-exact-descriptor-data ()
  (uwumacs-registry-test-with-registry
    (dolist (spec '((:priority 3) (:features "bad") (:modes (nil))
                    (:requires (4)) (:features nil :features nil)
                    (:initial-state beacon) (:setup 2) (:capability 3)
                    (:leader-bindings (([120] ignore "x")))
                    (:local-bindings (("x" ignore 7)))
                    (:state-bindings ((insert "j" next-line)))
                    (:leader-bindings (("x" nil "x")))))
      (should-error (apply #'uwumacs-register-integration 'bad spec)))
    (should-not uwumacs--registry)
    (should (eq 'fine (uwumacs-register-integration 'fine :features '(files))))))

(ert-deftest uwumacs-registry-cycle-and-disabled-dependencies ()
  (uwumacs-registry-test-with-registry
    (uwumacs-register-integration 'a :requires '(b))
    (should-error (uwumacs-register-integration 'b :requires '(a)))
    (should-not (assq 'b uwumacs--registry))
    (uwumacs-register-integration 'b)
    (should (eq 'unavailable (uwumacs-enable-integration 'a)))
    (should-not (memq 'b uwumacs-integrations))
    (should (string-match-p "b" (plist-get (cdr (assq 'a uwumacs--registry)) :reason)))
    (uwumacs-enable-integration 'b)
    (should (eq 'ready (uwumacs-registry-test-status 'a)))
    (should-error (uwumacs-disable-integration 'b))
    (uwumacs-disable-integration 'a)
    (uwumacs-disable-integration 'b)))

(ert-deftest uwumacs-registry-setup-cleanup-reload-and-mode-lifetime ()
  (uwumacs-registry-test-with-registry
    (let* ((setups 0) (cleanups 0)
           (setup (lambda () (cl-incf setups) (lambda () (cl-incf cleanups)))))
      (uwumacs-register-integration 'one :setup setup)
      (dotimes (_ 2) (uwumacs-enable-integration 'one))
      (uwumacs-register-integration 'one :setup setup)
      (uwumacs-refresh)
      (should (= setups 1))
      (dotimes (_ 2) (uwumacs-disable-integration 'one))
      (should (= cleanups 1))
      (uwumacs-enable-integration 'one)
      (uwumacs-mode -1)
      (should (= cleanups 2))
      (should-not uwumacs-map-context-function)
      (should-not (memq #'uwumacs--registry-after-load after-load-functions))
      (uwumacs-mode 1)
      (should (= setups 3)))))

(ert-deftest uwumacs-registry-missing-library-capability-and-command ()
  (uwumacs-registry-test-with-registry
    (uwumacs-register-integration 'absent :features '(uwumacs-no-such-library))
    (should (eq 'unavailable (uwumacs-enable-integration 'absent)))
    (uwumacs-register-integration 'cap :capability (lambda () "missing fixture executable"))
    (should (eq 'unavailable (uwumacs-enable-integration 'cap)))
    (uwumacs-register-integration 'command :leader-bindings '(("z" uwumacs-missing-command "Missing")))
    (should (eq 'pending (uwumacs-enable-integration 'command)))
    (should-not (keymap-lookup uwumacs--buffer-leader-map "z"))
    (should (string-match-p "uwumacs-missing-command" (plist-get (cdr (assq 'command uwumacs--registry)) :reason)))
    (uwumacs-doctor)
    (with-current-buffer "*UwUmacs Doctor*"
      (should (string-match-p "missing fixture executable" (buffer-string))))))

(ert-deftest uwumacs-registry-pending-autoload-and-disable-before-load ()
  (uwumacs-registry-test-with-registry
    (let* ((directory (make-temp-file "uwu-lazy-" t))
           (load-path (cons directory load-path)) (calls 0)
           (file (expand-file-name "uwumacs-lazy-fixture.el" directory)))
      (unwind-protect
          (progn
            (with-temp-file file
              (insert ";;; -*- lexical-binding: t; -*-\n(defun uwumacs-lazy-command () (interactive))\n(provide 'uwumacs-lazy-fixture)\n"))
            (autoload 'uwumacs-lazy-command "uwumacs-lazy-fixture" nil t)
            (uwumacs-register-integration 'lazy :features '(uwumacs-lazy-fixture)
              :leader-bindings '(("z" uwumacs-lazy-command "Lazy"))
              :setup (lambda () (cl-incf calls) nil))
            (should (eq 'pending (uwumacs-enable-integration 'lazy)))
            (should-not (featurep 'uwumacs-lazy-fixture))
            (should (eq 'uwumacs-lazy-command (keymap-lookup uwumacs--buffer-leader-map "z")))
            (uwumacs-disable-integration 'lazy)
            (load file nil t)
            (should (eq 'disabled (uwumacs-registry-test-status 'lazy)))
            (should (= calls 0))
            (should (eq 'ready (uwumacs-enable-integration 'lazy)))
            (should (= calls 1)))
        (uwumacs-disable-integration 'lazy)
        (when (featurep 'uwumacs-lazy-fixture) (unload-feature 'uwumacs-lazy-fixture t))
        (fmakunbound 'uwumacs-lazy-command)
        (delete-directory directory t)))))

(ert-deftest uwumacs-registry-mode-entry-setup-and-initial-state-once ()
  (uwumacs-registry-test-with-registry
    (let ((calls 0))
      (uwumacs-register-integration 'parent :modes '(uwumacs-registry-parent-mode)
        :initial-state 'motion :setup (lambda () (cl-incf calls) nil)
        :local-bindings '(("x" ignore "X")))
      (should (eq 'pending (uwumacs-enable-integration 'parent)))
      (with-temp-buffer
        (meow-mode 1)
        (uwumacs-registry-child-mode)
        (meow-mode 1)
        (uwumacs--registry-context-entry)
        (should (eq 'ready (uwumacs-registry-test-status 'parent)))
        (should (eq 'ignore (keymap-lookup (uwumacs-localleader-map) "x")))
        (should (bound-and-true-p meow-motion-mode))
        (meow-insert-mode 1)
        (dotimes (_ 3) (uwumacs-refresh))
        (should (bound-and-true-p meow-insert-mode)))
      (with-temp-buffer (uwumacs-registry-child-mode))
      (should (= calls 1)))))

(ert-deftest uwumacs-registry-specificity-user-overrides-and-committed-metadata ()
  (uwumacs-registry-test-with-registry
    (with-temp-buffer
      (uwumacs-registry-child-mode)
      (uwumacs-register-integration 'parent :modes '(uwumacs-registry-parent-mode)
        :local-bindings '(("x" ignore "Parent") ("p" backward-char "Inherited")))
      (uwumacs-register-integration 'child :modes '(uwumacs-registry-child-mode)
        :local-bindings '(("x" forward-char "Child")))
      (uwumacs-enable-integration 'parent)
      (uwumacs-enable-integration 'child)
      (should (eq 'forward-char (keymap-lookup (uwumacs-localleader-map) "x")))
      (should (eq 'backward-char (keymap-lookup (uwumacs-localleader-map) "p")))
      (dotimes (_ 3) (uwumacs-refresh))
      (should (eq 'child (plist-get (uwumacs--binding-metadata "x" (plist-get uwumacs--buffer-metadata :localleader)) :owner)))
      (keymap-set uwumacs-localleader-map "x" #'beginning-of-line)
      (uwumacs-refresh)
      (should (eq 'beginning-of-line (keymap-lookup (uwumacs-localleader-map) "x"))))))

(ert-deftest uwumacs-registry-conflict-and-invalid-replacement-are-atomic ()
  (uwumacs-registry-test-with-registry
    (uwumacs-register-integration 'one :leader-bindings '(("z" ignore "One")))
    (uwumacs-enable-integration 'one)
    (let ((map uwumacs--buffer-leader-map) (registry uwumacs--registry))
      (should-error (uwumacs-register-integration 'one :leader-bindings '(("f f" forward-char "Conflict"))))
      (should (eq map uwumacs--buffer-leader-map))
      (should (equal registry uwumacs--registry)))
    (uwumacs-register-integration 'two :leader-bindings '(("z" forward-char "Two")))
    (let ((map uwumacs--buffer-leader-map))
      (let ((err (should-error (uwumacs-enable-integration 'two))))
        (should (string-match-p "one" (error-message-string err)))
        (should (string-match-p "two" (error-message-string err))))
      (should (eq map uwumacs--buffer-leader-map))
      (should-not (memq 'two uwumacs-integrations))
      (should (string-match-p "two" (or uwumacs--registry-diagnostic ""))))))

(ert-deftest uwumacs-registry-override-hook-and-failed-setup-cleanup ()
  (uwumacs-registry-test-with-registry
    (let ((cleanups 0) (hooks 0))
      (add-hook 'uwumacs-after-integration-hook
                (lambda (id) (cl-incf hooks)
                  (when (eq id 'broken) (error "override failed"))
                  (keymap-set uwumacs-user-leader-map "z" #'backward-char)))
      (uwumacs-register-integration 'good :leader-bindings '(("z" ignore "Good")))
      (uwumacs-enable-integration 'good)
      (should (eq 'backward-char (keymap-lookup uwumacs--buffer-leader-map "z")))
      (uwumacs-register-integration 'broken :setup (lambda () (lambda () (cl-incf cleanups))))
      (should (eq 'failed (uwumacs-enable-integration 'broken)))
      (should (= cleanups 1))
      (uwumacs-refresh)
      (should (= hooks 2))
      (uwumacs-register-integration 'raises :setup (lambda () (error "setup failed")))
      (should (eq 'failed (uwumacs-enable-integration 'raises)))
      (uwumacs-doctor)
      (with-current-buffer "*UwUmacs Doctor*"
        (should (string-match-p "setup failed" (buffer-string)))))))

(ert-deftest uwumacs-registry-pending-mode-leader-is-global ()
  (uwumacs-registry-test-with-registry
    (let ((setups 0))
      (uwumacs-register-integration 'mode :modes '(uwumacs-registry-parent-mode)
        :leader-bindings '(("z" ignore "Open"))
        :setup (lambda () (cl-incf setups) nil))
      (should (eq 'pending (uwumacs-enable-integration 'mode)))
      (with-temp-buffer
        (text-mode)
        (should (eq 'ignore (key-binding (kbd "C-c C-SPC z"))))
        (should (= setups 0)))
      (with-temp-buffer
        (uwumacs-registry-child-mode)
        (should (= setups 1)))
      (with-temp-buffer (text-mode) (uwumacs-refresh) (should (= setups 1)))
      (uwumacs-register-integration 'other :modes '(text-mode)
        :leader-bindings '(("z" forward-char "Other")))
      (should-error (uwumacs-enable-integration 'other)))))

(ert-deftest uwumacs-registry-feature-load-readies-pending-once ()
  (uwumacs-registry-test-with-registry
    (let* ((directory (make-temp-file "uwu-ready-" t))
           (load-path (cons directory load-path)) (calls 0)
           (file (expand-file-name "uwumacs-ready-fixture.el" directory)))
      (unwind-protect
          (progn
            (with-temp-file file (insert ";;; -*- lexical-binding: t; -*-\n(provide 'uwumacs-ready-fixture)\n"))
            (uwumacs-register-integration 'lazy :features '(uwumacs-ready-fixture)
              :setup (lambda () (cl-incf calls) nil))
            (should (eq 'pending (uwumacs-enable-integration 'lazy)))
            (load file nil t)
            (should (eq 'ready (uwumacs-registry-test-status 'lazy)))
            (load file nil t)
            (should (= calls 1)))
        (uwumacs-disable-integration 'lazy)
        (when (featurep 'uwumacs-ready-fixture) (unload-feature 'uwumacs-ready-fixture t))
        (delete-directory directory t)))))

(ert-deftest uwumacs-registry-failed-replacement-retires-dependent-effects ()
  (uwumacs-registry-test-with-registry
    (let ((events nil))
      (uwumacs-register-integration 'base :setup (lambda () (push 'base-start events) (lambda () (push 'base-stop events))))
      (uwumacs-register-integration 'child :requires '(base)
        :setup (lambda () (push 'child-start events) (lambda () (push 'child-stop events))))
      (uwumacs-enable-integration 'base)
      (uwumacs-enable-integration 'child)
      (uwumacs-register-integration 'base :setup (lambda () (error "new setup failed")))
      (should (eq 'failed (uwumacs-registry-test-status 'base)))
      (should (eq 'unavailable (uwumacs-registry-test-status 'child)))
      (should (memq 'child-stop events))
      (should (= 1 (cl-count 'base-stop events)))
      (should (= 1 (cl-count 'child-stop events))))))

(ert-deftest uwumacs-registry-valid-replacement-preserves-native-user-overrides ()
  (uwumacs-registry-test-with-registry
    (let ((cleanups 0))
      (uwumacs-register-integration 'one :leader-bindings '(("z" ignore "Old"))
        :setup (lambda () (lambda () (cl-incf cleanups))))
      (uwumacs-enable-integration 'one)
      (keymap-set uwumacs-user-leader-map "z" #'backward-char)
      (uwumacs-register-integration 'one :leader-bindings '(("z" forward-char "New")))
      (should (= cleanups 1))
      (should (eq 'backward-char (keymap-lookup uwumacs--buffer-leader-map "z")))
      (should (equal "New" (plist-get (uwumacs--binding-metadata "z" (plist-get uwumacs--buffer-metadata :leader)) :label))))))

(ert-deftest uwumacs-registry-hook-map-conflict-fails-and-cleans ()
  (uwumacs-registry-test-with-registry
    (let ((uwumacs-leader-map (copy-keymap uwumacs-leader-map)) (cleanups 0))
      (add-hook 'uwumacs-after-integration-hook
                (lambda (_) (keymap-set uwumacs-leader-map "z" #'forward-char)))
      (uwumacs-register-integration 'one :leader-bindings '(("z" ignore "One"))
        :setup (lambda () (lambda () (cl-incf cleanups))))
      (should (eq 'failed (uwumacs-enable-integration 'one)))
      (should (= cleanups 1))
      (should (eq 'forward-char (keymap-lookup uwumacs--buffer-leader-map "z")))
      (should (eq 'public-base (plist-get (uwumacs--binding-metadata "z" (plist-get uwumacs--buffer-metadata :leader)) :owner))))))

(ert-deftest uwumacs-registry-rejects-ambiguous-initial-state ()
  (uwumacs-registry-test-with-registry
    (with-temp-buffer
      (uwumacs-registry-child-mode)
      (uwumacs-register-integration 'one :modes '(uwumacs-registry-parent-mode) :initial-state 'motion)
      (uwumacs-register-integration 'two :modes '(uwumacs-registry-parent-mode) :initial-state 'normal)
      (uwumacs-enable-integration 'one)
      (should-error (uwumacs-enable-integration 'two)))))

(ert-deftest uwumacs-registry-rejects-self-conflicting-unselected-descriptor ()
  (uwumacs-registry-test-with-registry
    (should-error (uwumacs-register-integration 'bad :local-bindings '(("x" ignore "One") ("x" forward-char "Two"))))
    (should-not (assq 'bad uwumacs--registry))))

(ert-deftest uwumacs-registry-buffer-refresh-preserves-unselected-buffer-snapshot ()
  (uwumacs-registry-test-with-registry
    (let ((one (generate-new-buffer " uwu-refresh-one"))
          (two (generate-new-buffer " uwu-refresh-two")))
      (unwind-protect
          (progn
            (uwumacs-refresh)
            (let ((snapshot (buffer-local-value 'uwumacs--buffer-leader-map two)))
              (uwumacs-refresh one)
              (should (eq snapshot (buffer-local-value 'uwumacs--buffer-leader-map two)))))
        (kill-buffer one) (kill-buffer two)))))

(ert-deftest uwumacs-registry-invalid-autoload-is-not-offered ()
  (uwumacs-registry-test-with-registry
    (unwind-protect
        (progn
          (autoload 'uwumacs-invalid-autoload "uwumacs-no-such-autoload" nil t)
          (uwumacs-register-integration 'bad :leader-bindings '(("z" uwumacs-invalid-autoload "Invalid")))
          (should (eq 'pending (uwumacs-enable-integration 'bad)))
          (should-not (keymap-lookup uwumacs--buffer-leader-map "z")))
      (fmakunbound 'uwumacs-invalid-autoload))))

(ert-deftest uwumacs-registry-late-hook-invalid-map-never-publishes-new-readiness ()
  (uwumacs-registry-test-with-registry
    (let ((cleanups 0) (snapshot uwumacs--buffer-leader-map))
      (uwumacs-register-integration 'two)
      (uwumacs-register-integration 'one :setup (lambda () (lambda () (cl-incf cleanups))))
      (setq snapshot uwumacs--buffer-leader-map)
      (add-hook 'uwumacs-after-integration-hook
                (lambda (id) (when (eq id 'two)
                               (keymap-set uwumacs-user-leader-map "m" #'ignore))))
      (setq uwumacs-integrations '(one two))
      (uwumacs-refresh)
      (should (eq 'failed (uwumacs-registry-test-status 'one)))
      (should (eq 'failed (uwumacs-registry-test-status 'two)))
      (should (= cleanups 1))
      (should (eq snapshot uwumacs--buffer-leader-map))
      ;; The registry must not roll back a direct mutation of the user's map.
      (should (eq 'ignore (keymap-lookup uwumacs-user-leader-map "m")))
      (keymap-unset uwumacs-user-leader-map "m"))))

(ert-deftest uwumacs-registry-selected-order-precedes-registration-order ()
  (uwumacs-registry-test-with-registry
    (let (events)
      (uwumacs-register-integration 'one :setup (lambda () (push 'one events) nil))
      (uwumacs-register-integration 'two :setup (lambda () (push 'two events) nil))
      (setq uwumacs-integrations '(one two))
      (uwumacs-refresh)
      (should (equal '(two one) events)))))

(ert-deftest uwumacs-registry-callback-mutations-fail-without-nested-commit ()
  (dolist (operation '(disable enable register))
    (uwumacs-registry-test-with-registry
      (let ((setups 0) (cleanups 0))
        (uwumacs-register-integration 'other :leader-bindings '(("y" forward-char "Other")))
        (uwumacs-register-integration 'one :leader-bindings '(("z" ignore "One"))
          :setup (lambda () (cl-incf setups) (lambda () (cl-incf cleanups))))
        (let ((original (copy-tree (uwumacs--descriptor 'other))))
          (add-hook 'uwumacs-after-integration-hook
                    (lambda (id)
                      (when (eq id 'one)
                        (pcase operation
                          ('disable (uwumacs-disable-integration id))
                          ('enable (uwumacs-enable-integration 'other))
                          ('register (uwumacs-register-integration 'other
                                       :leader-bindings '(("q" backward-char "Changed"))))))))
          (should (eq 'failed (uwumacs-enable-integration 'one)))
          (should (equal uwumacs-integrations '(one)))
          (should (equal original (uwumacs--descriptor 'other)))
          (should (eq 'disabled (uwumacs-registry-test-status 'other)))
          (should (string-match-p "registry callback" (plist-get (alist-get 'one uwumacs--registry) :reason)))
          (should-not (keymap-lookup uwumacs--buffer-leader-map "z"))
          (should-not (keymap-lookup uwumacs--buffer-leader-map "y"))
          (dotimes (_ 3) (uwumacs-refresh))
          (should (equal uwumacs-integrations '(one)))
          (should (eq 'failed (uwumacs-registry-test-status 'one)))
          (should (= setups 1))
          (should (= cleanups 1))
          ;; Explicit disable/re-enable remains a supported retry boundary.
          (setq uwumacs-after-integration-hook nil)
          (uwumacs-disable-integration 'one)
          (should (eq 'ready (uwumacs-enable-integration 'one)))
          (should (= setups 2))
          (should (= cleanups 1)))))))

(ert-deftest uwumacs-registry-setup-cannot-register-another-integration ()
  (uwumacs-registry-test-with-registry
    (let ((attempts 0))
      (uwumacs-register-integration 'one
        :setup (lambda () (cl-incf attempts) (uwumacs-register-integration 'nested)))
      (should (eq 'failed (uwumacs-enable-integration 'one)))
      (should-not (assq 'nested uwumacs--registry))
      (dotimes (_ 3) (uwumacs-refresh))
      (should (= attempts 1)))))

(ert-deftest uwumacs-registry-cleanup-cannot-enable-another-integration ()
  (uwumacs-registry-test-with-registry
    (let ((cleanups 0))
      (uwumacs-register-integration 'other)
      (uwumacs-register-integration 'one
        :setup (lambda ()
                 (lambda ()
                   (cl-incf cleanups)
                   (should-error (uwumacs-enable-integration 'other)))))
      (uwumacs-enable-integration 'one)
      (uwumacs-disable-integration 'one)
      (should-not uwumacs-integrations)
      (should (eq 'disabled (uwumacs-registry-test-status 'other)))
      (uwumacs-refresh)
      (should (= cleanups 1)))))

(ert-deftest uwumacs-registry-callback-refresh-is-coalesced-with-user-overrides ()
  (uwumacs-registry-test-with-registry
    (let ((setups 0) (callbacks 0))
      (uwumacs-register-integration 'one :leader-bindings '(("z" ignore "One"))
        :setup (lambda () (cl-incf setups) nil))
      (add-hook 'uwumacs-after-integration-hook
                (lambda (_)
                  (cl-incf callbacks)
                  (keymap-set uwumacs-user-leader-map "z" #'forward-char)
                  (uwumacs-refresh)))
      (should (eq 'ready (uwumacs-enable-integration 'one)))
      (should (eq 'forward-char (keymap-lookup uwumacs--buffer-leader-map "z")))
      (uwumacs-refresh)
      (should (= setups 1))
      (should (= callbacks 1)))))

(ert-deftest uwumacs-registry-callback-cannot-partially-disable-global-mode ()
  (uwumacs-registry-test-with-registry
    (let ((setups 0) (cleanups 0))
      (uwumacs-register-integration 'one :leader-bindings '(("z" ignore "One"))
        :setup (lambda () (cl-incf setups) (lambda () (cl-incf cleanups))))
      (add-hook 'uwumacs-after-integration-hook (lambda (_) (uwumacs-mode -1)))
      (should (eq 'failed (uwumacs-enable-integration 'one)))
      (should uwumacs-mode)
      (should uwumacs--installed)
      (should (eq uwumacs-map-context-function #'uwumacs--registry-sources))
      (should (memq 'uwumacs--emulation-alist emulation-mode-map-alists))
      (should (memq #'uwumacs--registry-after-load after-load-functions))
      (should (memq #'uwumacs--observe-buffer after-change-major-mode-hook))
      (should (equal uwumacs-integrations '(one)))
      (should-not (keymap-lookup uwumacs--buffer-leader-map "z"))
      (should (eq 'find-file (key-binding (kbd "C-c C-SPC f f"))))
      (dotimes (_ 3) (uwumacs-refresh))
      (should (= setups 1))
      (should (= cleanups 1)))))

(ert-deftest uwumacs-registry-cleanup-cannot-partially-enable-global-mode ()
  (uwumacs-registry-test-with-registry
    (let ((cleanups 0))
      (uwumacs-register-integration 'one
        :setup (lambda () (lambda () (cl-incf cleanups) (uwumacs-mode 1))))
      (uwumacs-enable-integration 'one)
      (uwumacs-mode -1)
      (should-not uwumacs-mode)
      (should-not uwumacs--installed)
      (should-not uwumacs-map-context-function)
      (should-not (memq 'uwumacs--emulation-alist emulation-mode-map-alists))
      (should-not (memq #'uwumacs--registry-after-load after-load-functions))
      (should-not (memq #'uwumacs--observe-buffer after-change-major-mode-hook))
      (should (eq 'failed (uwumacs-registry-test-status 'one)))
      (should (equal uwumacs-integrations '(one)))
      (uwumacs-refresh)
      (should (= cleanups 1)))))
